name: Check Dependencies

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu projeto

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13  # Especifique a versão do Python que você está usando

      - name: Install dependencies
        run: pip install flask tensorflow numpy keras Pillow

      - name: Run main.py
        run: python main.py