name: Check requirements.txt

on:
  push:
    branches:
      - main

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      - name: Install Node.js
        uses: actions/setup-node@v2
        
      - name: Install pipdeptree
        run: |

          pip install pipdeptree
          
      - name: Check requirements.txt
        run: |

          pipdeptree -r requirements.txt