name: Check Dependencies

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu projeto

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13  # Especifique a versão do Python que você está usando

      - name: Install dependencies
        run: pip install flask tensorflow numpy keras

      - name: Check dependencies
        run: |
          installed_packages=$(pip freeze)
          required_packages=$(cat requirements.txt)
          missing_packages=""
          
          for package in $required_packages; do
            if ! echo "$installed_packages" | grep -q "^$package=="; then
              missing_packages="$missing_packages $package"
            fi
          done

          if [ -n "$missing_packages" ]; then
            echo "Missing dependencies: $missing_packages"
            exit 1
          else
            echo "All dependencies are satisfied."
          fi